name: learnk8s
url: https://learnk8s.io
video_course: no
exclude:
  - node_modules
  - yarn.lock
  - docker-compose.yml
  - package.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
sass:
  load_paths:
    - node_modules
  style: compressed
excerpt_separator: <!--more-->
post_limit: 5
collections:
  blog:
    output: true
    permalink: /blog/:path
  pages:
    output: true
    permalink: /:path
  newsletter:
    output: true
    permalink: /newsletter/:path
defaults:
  - scope:
      path: ""
      type: "newsletter"
    values:
      layout: "newsletter"
plugins:
  - jekyll-target-blank
  - jekyll-sitemap

target-blank:
  css_class: ext-link
