[build]
  base    = "."
  publish = "_site"
  command = "npm install && npm run fmt && npm run build"
[context.deploy-preview]
  NODE_ENV = "preview"
  command = "npm install && mkdir -p _site && echo -e \"\nDisallow: /\" >> _site/robots.txt && npm run fmt && npm run build"
[context.production.environment]
  NODE_ENV = "production"
[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31556926"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31556926"
[[headers]]
  for = "*.svg" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31556926"
[[headers]]
  for = "*.png" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31556926"
[[headers]]
  for = "*.jpg" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31556926"